---
- name: Deploy container to AKS
  hosts: localhost
  gather_facts: yes
  vars:
    aks_cluster_name: "avrcp2aks"
    deployment_file_path: "~/avr/unir/repo/unir-devops-cp2/cp2/ansible/aks_deployment.yml"  # Full path to the deployment file
    acr_name: "{{ lookup('env', 'ACR_NAME') }}"
    acr_username: "{{ lookup('env', 'CLIENT_ID') }}"
    acr_password: "{{ lookup('env', 'CLIENT_SECRET') }}"
    acr_server: "{{ acr_name }}.azurecr.io"

  tasks:
    - name: Login to Azure CLI
      ansible.builtin.command: >
        az login --service-principal
        --username "{{ lookup('env', 'CLIENT_ID') }}"
        --password "{{ lookup('env', 'CLIENT_SECRET') }}"
        --tenant "{{ lookup('env', 'TENANT_ID') }}"

    - name: Set Azure subscription
      ansible.builtin.command: >
        az account set --subscription "{{ lookup('env', 'SUBSCRIPTION_ID') }}"


    - name: Get ACR login access token
      ansible.builtin.command: >
        az acr login --name {{ lookup('env', 'ACR_NAME') }} --expose-token
      register: acr_login_result

    - name: Parse ACR login access token
      set_fact:
        acr_access_token: "{{ acr_login_result.stdout | from_json | json_query('accessToken') }}"

    - name: Get AKS credentials
      ansible.builtin.command: >
        az aks get-credentials --resource-group "{{ lookup('env', 'RESOURCE_GROUP') }}" --name "{{ aks_cluster_name }}" --overwrite-existing

    - name: Ensure namespace exists
      ansible.builtin.command: >
        kubectl apply -f -
      args:
        stdin: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: avrakscp2

    - name: Create Docker registry secret for ACR
      shell: >
        kubectl create secret docker-registry acr-secret
        --docker-server="{{ acr_server }}"
        --docker-username="{{ acr_username }}"
        --docker-password="{{ acr_password }}"
        --docker-email="vierodan@gmail.com"
        -n avrakscp2
      register: acr_secret_result
      ignore_errors: true
    
    - name: Apply Kubernetes deployment
      ansible.builtin.command: >
        kubectl -n avrakscp2 apply -f "{{ deployment_file_path }}"

    - name: Get AKS services
      ansible.builtin.command: >
        kubectl get services -n avrakscp2
      register: aks_services

    - name: Print AKS services
      debug:
        msg: "{{ aks_services.stdout }}"