---
- name: Calculate AKS public IP
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Wait for AKS service frontend to be created
      kubernetes.core.k8s_info:
        kind: Service
        namespace: avrakscp2
        name: frontend
      register: service_info
      until: service_info.resources[0].status.loadBalancer.ingress | default([]) | length > 0
      retries: 10
      delay: 10

    - name: Get the public IP of the AKS service
      ansible.builtin.set_fact:
        public_ip: "{{ service_info.resources[0].status.loadBalancer.ingress[0].ip }}"

    - name: Display the public IP of AKS frontend app
      ansible.builtin.debug:
        msg: "The public IP of the AKS service is {{ public_ip }}"
