---
- name: Deploy nginx image to Azure Container Registry
  hosts: localhost
  gather_facts: no
  vars:
    back_source_image: docker://nginx:latest
    back_destination_image: .azurecr.io/nginx:cp2
    arch: amd64
    os: linux

  tasks:
    - name: Login to Azure CLI
      ansible.builtin.command: >
        az login --service-principal
        --username "{{ lookup('env', 'CLIENT_ID') }}"
        --password "{{ lookup('env', 'CLIENT_SECRET') }}"
        --tenant "{{ lookup('env', 'TENANT_ID') }}"

    - name: Set Azure subscription
      ansible.builtin.command: >
        az account set --subscription "{{ lookup('env', 'SUBSCRIPTION_ID') }}"


    - name: Get ACR login access token
      ansible.builtin.command: >
        az acr login --name {{ lookup('env', 'ACR_NAME') }} --expose-token
      register: acr_login_result

    - name: Parse ACR login access token
      set_fact:
        acr_access_token: "{{ acr_login_result.stdout | from_json | json_query('accessToken') }}"

    - name: Log in to Azure Container Registry with Podman using access token
      ansible.builtin.command: >
        podman login {{ lookup('env', 'ACR_NAME') }}.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p "{{ acr_access_token }}"
      register: login_result
      ignore_errors: yes

    - name: Fail if login to ACR failed
      fail:
        msg: "Failed to log in to Azure Container Registry"
      when: login_result.rc != 0


    - name: Copy back image from source to Azure Container Registry
      command: skopeo copy --override-arch {{ arch }} --override-os {{ os }} {{ back_source_image }} docker://{{ lookup('env', 'ACR_NAME') }}{{ back_destination_image }}
      register: skopeo_copy
      failed_when: skopeo_copy.rc != 0

    - name: Display Skopeo copy result
      debug:
        var: skopeo_copy.stdout_lines