---
- name: Deploy Nginx Docker image to Azure Container Registry
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Login to Azure CLI
      ansible.builtin.command: >
        az login --service-principal
        --username "{{ lookup('env', 'CLIENT_ID') }}"
        --password "{{ lookup('env', 'CLIENT_SECRET') }}"
        --tenant "{{ lookup('env', 'TENANT_ID') }}"

    - name: Set Azure subscription
      ansible.builtin.command: >
        az account set --subscription "{{ lookup('env', 'SUBSCRIPTION_ID') }}"

    - name: Pull Nginx Docker image locally using Podman
      ansible.builtin.command: >
        podman pull docker://nginx:latest

    - name: Tag the Nginx Docker image for Azure Container Registry
      ansible.builtin.command: >
        podman tag nginx:latest {{ lookup('env', 'ACR_NAME') }}.azurecr.io/nginx:latest

    - name: Pull Azure Vote Front Microsoft image locally using Podman
      ansible.builtin.command: >
        podman pull mcr.microsoft.com/azuredocs/azure-vote-front:v1

    - name: Tag the Azure Vote Front Microsoft image for Azure Container Registry
      ansible.builtin.command: >
        podman tag azure-vote-front:v1 {{ lookup('env', 'ACR_NAME') }}.azurecr.io/azure-vote-front:v1

    - name: Pull Azure Vote Back Microsoft image locally using Podman
      ansible.builtin.command: >
        podman pull mcr.microsoft.com/oss/bitnami/redis:6.0.8

    - name: Tag the Azure Vote Back Microsoft image for Azure Container Registry
      ansible.builtin.command: >
        podman tag redis:6.0.8 {{ lookup('env', 'ACR_NAME') }}.azurecr.io/redis:6.0.8

    - name: Get ACR login access token
      ansible.builtin.command: >
        az acr login --name {{ lookup('env', 'ACR_NAME') }} --expose-token
      register: acr_login_result

    - name: Parse ACR login access token
      set_fact:
        acr_access_token: "{{ acr_login_result.stdout | from_json | json_query('accessToken') }}"

    - name: Log in to Azure Container Registry with Podman using access token
      ansible.builtin.command: >
        podman login {{ lookup('env', 'ACR_NAME') }}.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p "{{ acr_access_token }}"
      register: login_result
      ignore_errors: yes

    - name: Debug login result
      debug:
        var: login_result

    - name: Fail if login to ACR failed
      fail:
        msg: "Failed to log in to Azure Container Registry"
      when: login_result.rc != 0

    - name: Push Nginx Docker image to Azure Container Registry
      ansible.builtin.command: >
        podman push {{ lookup('env', 'ACR_NAME') }}.azurecr.io/nginx:latest

    - name: Push Azure Vote Front Microsoft image to Azure Container Registry
      ansible.builtin.command: >
        podman push {{ lookup('env', 'ACR_NAME') }}.azurecr.io/azure-vote-front:v1

    - name: Push Azure Vote Back Microsoft image to Azure Container Registry
      ansible.builtin.command: >
        podman push {{ lookup('env', 'ACR_NAME') }}.azurecr.io/redis:6.0.8
