---
- name: Install Software on Azure VM
  hosts: webserver
  gather_facts: yes
  remote_user: adminuser
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Podman
      ansible.builtin.apt:
        name: podman
        state: present

    - name: Modify registries.conf for unqualified search registries
      ansible.builtin.lineinfile:
        path: /etc/containers/registries.conf
        regexp: '^# unqualified-search-registries.*'
        line: 'unqualified-search-registries = ["docker.io"]'
        state: present

    - name: Install podman-docker
      ansible.builtin.apt:
        name: podman-docker
        state: present

    - name: Install buildah
      ansible.builtin.apt:
        name: buildah
        state: present

    - name: Install skopeo
      ansible.builtin.apt:
        name: skopeo
        state: present




